// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa28M68Mpem6ZHuOoHcS8tw-dIgD73Qgs',
    appId: '1:935177640739:web:db28fb5283058a854eca96',
    messagingSenderId: '935177640739',
    projectId: 'team-alarm1-2',
    authDomain: 'team-alarm1-2.firebaseapp.com',
    storageBucket: 'team-alarm1-2.firebasestorage.app',
    measurementId: 'G-M2S1X0K5WW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ayRbJ4rUTWiigPPpam5j5mVNyUSfYr4',
    appId: '1:935177640739:android:5baa1bae355d1edd4eca96',
    messagingSenderId: '935177640739',
    projectId: 'team-alarm1-2',
    storageBucket: 'team-alarm1-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf8UAT9inK0o6sRzlErSryu31YVDwcqwc',
    appId: '1:935177640739:ios:f2ea2fdf339e1bae4eca96',
    messagingSenderId: '935177640739',
    projectId: 'team-alarm1-2',
    storageBucket: 'team-alarm1-2.firebasestorage.app',
    iosBundleId: 'nagomin.alarm12.teamAlarm12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf8UAT9inK0o6sRzlErSryu31YVDwcqwc',
    appId: '1:935177640739:ios:f2ea2fdf339e1bae4eca96',
    messagingSenderId: '935177640739',
    projectId: 'team-alarm1-2',
    storageBucket: 'team-alarm1-2.firebasestorage.app',
    iosBundleId: 'nagomin.alarm12.teamAlarm12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa28M68Mpem6ZHuOoHcS8tw-dIgD73Qgs',
    appId: '1:935177640739:web:6b9e7e23320a61314eca96',
    messagingSenderId: '935177640739',
    projectId: 'team-alarm1-2',
    authDomain: 'team-alarm1-2.firebaseapp.com',
    storageBucket: 'team-alarm1-2.firebasestorage.app',
    measurementId: 'G-L7WD9B0LXL',
  );

}