name: Flutter CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ★ Flutter をセットアップ（これが無いと "flutter: command not found"）
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'   # 使用中のFlutterに合わせて（未指定ならstable最新でもOK）
          channel: 'stable'
          cache: true                 # pubキャッシュを自動保存（高速化）

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --no-pub
